name: Telegram Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        run: |
          curl -s -X POST https://api.telegram.org{{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="🚀 GitHub 연결 성공!%0A작성자: ${{ github.actor }}%0A메시지: ${{ github.event.head_commit.message }}"
