name: Telegram Notification
on: [push] # 푸시(업로드)할 때마다 알림 전송

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 GitHub에 새로운 푸시가 발생했습니다!
            - 레포지토리: ${{ github.repository }}
            - 작성자: ${{ github.actor }}
            - 커밋 내용: ${{ github.event.commits[0].message }}
            - 확인하기: https://github.com{{ github.repository }}/commit/${{ github.sha }}





